=== GoogleCloudPlatform/telco-autonomous-networks-data-demo/infrastructure/terraform/vertex-ai-schema/rca-rules.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "dynamic": "true",
  "properties": {
    "description": {
      "type": "string",
      "keyPropertyMapping": "description",
      "retrievable": true
    },
    "kpi_missed": {
      "type": "array",
      "items": {
        "type": "string",
        "keyPropertyMapping": "category"
      }
    },
    "processing_rule": {
      "type": "string",
      "indexable": true,
      "retrievable": true,
      "dynamicFacetable": true,
      "searchable": true
    },
    "processing_rule_tools": {
      "type": "array",
      "items": {
        "type": "string",
        "retrievable": true,
        "searchable": true
      }
    },
    "severity_determination_rule": {
      "type": "string",
      "indexable": true,
      "retrievable": true,
      "dynamicFacetable": true,
      "searchable": true
    },
    "severity_determination_rule_tools": {
      "type": "array",
      "items": {
        "type": "string",
        "retrievable": true,
        "searchable": true
      }
    },
    "vendor": {
      "type": "string",
      "indexable": true,
      "retrievable": true,
      "dynamicFacetable": true,
      "searchable": true
    },
    "author": {
      "type": "string",
      "indexable": true,
      "retrievable": true,
      "dynamicFacetable": true,
      "searchable": true
    },
    "creation_date": {
      "type": "datetime",
      "indexable": true,
      "retrievable": true
    },
    "is_current": {
      "type": "boolean",
      "indexable": true,
      "retrievable": true
    }
  }
}

=== GoogleCloudPlatform/telco-autonomous-networks-data-demo/data/rca-rules/erab-success-rate-below-threshold.json
{
  "description": "eRAB success rate below threshold",
  "kpi_missed": [
    "erab_success_rate"
  ],
  "processing_rule": "Check if the cell traces for the enodeb and cell which mised the KPI indicate security failures. If a sufficient percentage of those failures are related to the failed security setup - mention that as a possible cause and provide details of the percentages. Suggest further analysis of the individual phones which failed the security setup.",
  "processing_rule_tools": ["get_cell_trace_statistics"],
  "severity_determination_rule": "If the eRAB success rate is below 95% rate the incident as high severity, otherwise it's a low severity incident",
  "severity_determination_rule_tools": [],
  "vendor": "Acme Telco Appliances",
  "author": "Jack Smith (smith@example.com), Jane Lee (lee@example.com)",
  "creation_date": "2025-12-26 08:30:00 UTC",
  "is_current": true
}

=== GoogleCloudPlatform/telco-autonomous-networks-data-demo/data/rca-rules/ul-rssi-out-of-range.json
{
  "description": "UL-RSSI level is outside normal",
  "kpi_missed": [
    "ul-rssi-level"
  ],
  "processing_rule": "If UL RSSI is greater than -105 it should be investigated. Check the uplink configuration and see if pZeroNominalPucch value is close to the optimal -114 and pZeroNominalPusch is close to the optimal -100 values. Consider adjusting these configurations if they significantly different from the optimal. If UL RSSI is between -114 and -105dbm it should be monitored to check if KPIs are affected. UL RSSI within the -120 and -114 range is considered normal. UL RSSI lower than -120dbm is considered too low - check the cell status",
  "processing_rule_tools": ["get_uplink_configuration"],
  "severity_determination_rule": "If UL RSSI is greater than -105  it is a high severity case. UL RSSI lower than -120dbm is a medium severity. Any other value is low severity",
  "severity_determination_rule_tools": [],
  "vendor": "Acme Telco Appliances",
  "author": "Acme Telco Appliances",
  "creation_date": "2025-12-26 08:30:00 UTC",
  "is_current": true
}

=== GoogleCloudPlatform/telco-autonomous-networks-data-demo/data/rca-rules/high-call-drop-levels.json
{
  "description": "High call drop levels",
  "kpi_missed": [
    "retainability"
  ],
  "processing_rule": "Check the uplink (UL) RSSI level of the cell.  If the UL RSSI level is outside of the normal boundaries of -120 and -114, check the uplink configuration and see if the pZeroNominalPucch value is close to the optimal -114 and pZeroNominalPusch is close to the optimal -100 values. Consider adjusting these configurations if they differ from the optimal by more than 5%.",
  "processing_rule_tools": ["get_uplink_rssi_level","get_uplink_configuration", "initiate_uplink_configuration_adjustement"],
  "severity_determination_rule": "If retainability level is greater than 3.5  it is a high severity case. If the uplink (UL) RSSI lovel is lower than -120 the incident is of a medium severity. If the UL RSSI level above -105 it is a high severity case. Any other values mean that this is a low severity incident.",
  "severity_determination_rule_tools": ["get_uplink_rssi_level"],
  "vendor": "Acme Telco Appliances",
  "author": "Acme Telco Appliances",
  "creation_date": "2025-12-26 08:30:00 UTC",
  "is_current": true
}
